export const counselingFlowData = {
  chunks: [
    {
      chunk_name: "ask_name",
      message_count: 3,
      response_type: "text",
      response_name: "name",
      choice_count: 0,
      text_placeholder: "Type your name (e.g. John)",
    },
    {
      chunk_name: "ask_agenda",
      message_count: 3,
      response_type: "text",
      response_name: "agenda",
      choice_count: 0,
      text_placeholder: "Ask question",
    },
    {
      chunk_name: "agenda_long",
      message_count: 1,
      response_type: "none",
      response_name: null,
      choice_count: 0,
      text_placeholder: null,
    },
    {
      chunk_name: "agenda_short",
      message_count: 1,
      response_type: "none",
      response_name: null,
      choice_count: 0,
      text_placeholder: null,
    },
    {
      chunk_name: "agenda_tiny",
      message_count: 2,
      response_type: "none",
      response_name: null,
      choice_count: 0,
      text_placeholder: null,
    },
    {
      chunk_name: "ask_pray",
      message_count: 2,
      response_type: "choice",
      response_name: "pray",
      choice_count: 2,
      text_placeholder: null,
    },
    {
      chunk_name: "accept_pray",
      message_count: 1,
      response_type: "none",
      response_name: null,
      choice_count: 0,
      text_placeholder: null,
    },
    {
      chunk_name: "decline_pray",
      message_count: 1,
      response_type: "none",
      response_name: null,
      choice_count: 0,
      text_placeholder: null,
    },
    {
      chunk_name: "ask_ready",
      message_count: 2,
      response_type: "choice",
      response_name: "ready",
      choice_count: 2,
      text_placeholder: null,
    },
    {
      chunk_name: "answer_word",
      message_count: 1,
      response_type: "choice",
      response_name: "satisfaction",
      choice_count: 3,
      text_placeholder: null,
    },
    {
      chunk_name: "satisfaction_positive",
      message_count: 2,
      response_type: "text",
      response_name: "feedback",
      choice_count: 0,
      text_placeholder: "Type feedback",
    },
    {
      chunk_name: "satisfaction_neutral",
      message_count: 1,
      response_type: "text",
      response_name: "feedback",
      choice_count: 0,
      text_placeholder: "Type feedback",
    },
    {
      chunk_name: "satisfaction_negative",
      message_count: 2,
      response_type: "text",
      response_name: "feedback",
      choice_count: 0,
      text_placeholder: "Type feedback",
    },
    {
      chunk_name: "not_ready",
      message_count: 1,
      response_type: "none",
      response_name: null,
      choice_count: 0,
      text_placeholder: null,
    },
    {
      chunk_name: "announce_offline",
      message_count: 2,
      response_type: "none",
      response_name: null,
      choice_count: 0,
      text_placeholder: null,
    },
    {
      chunk_name: "announce_failure",
      message_count: 2,
      response_type: "none",
      response_name: null,
      choice_count: 0,
      text_placeholder: null,
    },
    {
      chunk_name: "announce_reject",
      message_count: 1,
      response_type: "none",
      response_name: null,
      choice_count: 0,
      text_placeholder: null,
    },
    {
      chunk_name: "feedback_long",
      message_count: 2,
      response_type: "none",
      response_name: null,
      choice_count: 0,
      text_placeholder: null,
    },
    {
      chunk_name: "feedback_short",
      message_count: 1,
      response_type: "none",
      response_name: null,
      choice_count: 0,
      text_placeholder: null,
    },
    {
      chunk_name: "ask_retry",
      message_count: 1,
      response_type: "choice",
      response_name: "retry",
      choice_count: 2,
      text_placeholder: null,
    },
    {
      chunk_name: "announce_end",
      message_count: 2,
      response_type: "none",
      response_name: null,
      choice_count: 0,
      text_placeholder: null,
    },
    {
      chunk_name: "next_agenda",
      message_count: 2,
      response_type: "text",
      response_name: "agenda",
      choice_count: 0,
      text_placeholder: "Ask question",
    },
  ],
  messages: [
    {
      chunk_name: "ask_name",
      message_order: 1,
      message_name: "introduce",
      message_code: "ask_name_introduce",
      line_count: 20,
      line_example: null,
    },
    {
      chunk_name: "ask_name",
      message_order: 2,
      message_name: "talk",
      message_code: "ask_name_talk",
      line_count: 25,
      line_example: null,
    },
    {
      chunk_name: "ask_name",
      message_order: 3,
      message_name: "ask",
      message_code: "ask_name_ask",
      line_count: 7,
      line_example: null,
    },
    {
      chunk_name: "ask_agenda",
      message_order: 1,
      message_name: "welcome",
      message_code: "ask_agenda_welcome",
      line_count: 21,
      line_example: null,
    },
    {
      chunk_name: "ask_agenda",
      message_order: 2,
      message_name: "ask",
      message_code: "ask_agenda_ask",
      line_count: 16,
      line_example: null,
    },
    {
      chunk_name: "ask_agenda",
      message_order: 3,
      message_name: "guide",
      message_code: "ask_agenda_guide",
      line_count: 9,
      line_example: null,
    },
    {
      chunk_name: "agenda_long",
      message_order: 1,
      message_name: "react",
      message_code: "agenda_long_react",
      line_count: 10,
      line_example: null,
    },
    {
      chunk_name: "agenda_short",
      message_order: 1,
      message_name: "react",
      message_code: "agenda_short_react",
      line_count: 9,
      line_example: null,
    },
    {
      chunk_name: "agenda_tiny",
      message_order: 1,
      message_name: "react",
      message_code: "agenda_tiny_react",
      line_count: 16,
      line_example: null,
    },
    {
      chunk_name: "agenda_tiny",
      message_order: 2,
      message_name: "ask",
      message_code: "agenda_tiny_ask",
      line_count: 6,
      line_example: null,
    },
    {
      chunk_name: "ask_pray",
      message_order: 1,
      message_name: "think",
      message_code: "ask_pray_think",
      line_count: 10,
      line_example: null,
    },
    {
      chunk_name: "ask_pray",
      message_order: 2,
      message_name: "ask",
      message_code: "ask_pray_ask",
      line_count: 4,
      line_example: null,
    },
    {
      chunk_name: "accept_pray",
      message_order: 1,
      message_name: "thank",
      message_code: "accept_pray_thank",
      line_count: 11,
      line_example: null,
    },
    {
      chunk_name: "decline_pray",
      message_order: 1,
      message_name: "react",
      message_code: "decline_pray_react",
      line_count: 7,
      line_example: null,
    },
    {
      chunk_name: "ask_ready",
      message_order: 1,
      message_name: "finish",
      message_code: "ask_ready_finish",
      line_count: 4,
      line_example: null,
    },
    {
      chunk_name: "ask_ready",
      message_order: 2,
      message_name: "ready",
      message_code: "ask_ready_ready",
      line_count: 4,
      line_example: null,
    },
    {
      chunk_name: "answer_word",
      message_order: 1,
      message_name: "suggest",
      message_code: "answer_word_suggest",
      line_count: 15,
      line_example: null,
    },
    {
      chunk_name: "satisfaction_positive",
      message_order: 1,
      message_name: "react",
      message_code: "satisfaction_positive_react",
      line_count: 18,
      line_example: null,
    },
    {
      chunk_name: "satisfaction_positive",
      message_order: 2,
      message_name: "ask",
      message_code: "satisfaction_positive_ask",
      line_count: 4,
      line_example: null,
    },
    {
      chunk_name: "satisfaction_neutral",
      message_order: 1,
      message_name: "ask",
      message_code: "satisfaction_neutral_ask",
      line_count: 6,
      line_example: null,
    },
    {
      chunk_name: "satisfaction_negative",
      message_order: 1,
      message_name: "react",
      message_code: "satisfaction_negative_react",
      line_count: 8,
      line_example: null,
    },
    {
      chunk_name: "satisfaction_negative",
      message_order: 2,
      message_name: "ask",
      message_code: "satisfaction_negative_ask",
      line_count: 5,
      line_example: null,
    },
    {
      chunk_name: "announce_offline",
      message_order: 1,
      message_name: "reason",
      message_code: "announce_offline_reason",
      line_count: 6,
      line_example: null,
    },
    {
      chunk_name: "announce_offline",
      message_order: 2,
      message_name: "retry",
      message_code: "announce_offline_retry",
      line_count: 7,
      line_example: null,
    },
    {
      chunk_name: "announce_failure",
      message_order: 1,
      message_name: "reason",
      message_code: "announce_failure_reason",
      line_count: 3,
      line_example: null,
    },
    {
      chunk_name: "announce_failure",
      message_order: 2,
      message_name: "retry",
      message_code: "announce_failure_retry",
      line_count: 6,
      line_example: null,
    },
    {
      chunk_name: "announce_reject",
      message_order: 1,
      message_name: "reason",
      message_code: "announce_reject_reason",
      line_count: 10,
      line_example: null,
    },
    {
      chunk_name: "not_ready",
      message_order: 1,
      message_name: "sorry",
      message_code: "not_ready_sorry",
      line_count: 9,
      line_example: null,
    },
    {
      chunk_name: "feedback_short",
      message_order: 1,
      message_name: "react",
      message_code: "feedback_short_react",
      line_count: 4,
      line_example: null,
    },
    {
      chunk_name: "feedback_long",
      message_order: 1,
      message_name: "react",
      message_code: "feedback_long_react",
      line_count: 4,
      line_example: null,
    },
    {
      chunk_name: "feedback_long",
      message_order: 2,
      message_name: "talk",
      message_code: "feedback_long_talk",
      line_count: 4,
      line_example: null,
    },
    {
      chunk_name: "ask_retry",
      message_order: 1,
      message_name: "ask",
      message_code: "ask_retry_ask",
      line_count: 3,
      line_example: null,
    },
    {
      chunk_name: "announce_end",
      message_order: 1,
      message_name: "react",
      message_code: "announce_end_react",
      line_count: 3,
      line_example: null,
    },
    {
      chunk_name: "announce_end",
      message_order: 2,
      message_name: "talk",
      message_code: "announce_end_talk",
      line_count: 12,
      line_example: null,
    },
    {
      chunk_name: "next_agenda",
      message_order: 1,
      message_name: "talk",
      message_code: "next_agenda_talk",
      line_count: 7,
      line_example: null,
    },
    {
      chunk_name: "next_agenda",
      message_order: 2,
      message_name: "ask",
      message_code: "next_agenda_ask",
      line_count: 4,
      line_example: null,
    },
  ],
  lines: [
    {
      message_code: "ask_name_introduce",
      line_case: 1,
      text: "Hi, I'm Jesus.",
      tone: null,
    },
    {
      message_code: "ask_name_introduce",
      line_case: 2,
      text: "Are you looking for me?",
      tone: null,
    },
    {
      message_code: "ask_name_introduce",
      line_case: 3,
      text: "Dear my child,",
      tone: null,
    },
    {
      message_code: "ask_name_introduce",
      line_case: 4,
      text: "Greetings and salutations, my child.",
      tone: null,
    },
    {
      message_code: "ask_name_introduce",
      line_case: 5,
      text: "Hello there!",
      tone: null,
    },
    {
      message_code: "ask_name_introduce",
      line_case: 6,
      text: "👋",
      tone: null,
    },
    {
      message_code: "ask_name_introduce",
      line_case: 7,
      text: "Greetings, earthling!",
      tone: null,
    },
    {
      message_code: "ask_name_introduce",
      line_case: 8,
      text: "Knock, knock.",
      tone: null,
    },
    {
      message_code: "ask_name_introduce",
      line_case: 9,
      text: "Yo!",
      tone: null,
    },
    {
      message_code: "ask_name_introduce",
      line_case: 10,
      text: "Hallelujah!",
      tone: null,
    },
    {
      message_code: "ask_name_introduce",
      line_case: 11,
      text: "Blessings to you, my child.",
      tone: null,
    },
    {
      message_code: "ask_name_introduce",
      line_case: 12,
      text: "Greetings, my friend.",
      tone: null,
    },
    {
      message_code: "ask_name_introduce",
      line_case: 13,
      text: "My name is Jesus.",
      tone: null,
    },
    {
      message_code: "ask_name_introduce",
      line_case: 14,
      text: "I am Jesus.",
      tone: null,
    },
    {
      message_code: "ask_name_introduce",
      line_case: 15,
      text: "I am the way, the truth, and the life.",
      tone: null,
    },
    {
      message_code: "ask_name_introduce",
      line_case: 16,
      text: "I'm Jesus, but you can call me JC.",
      tone: null,
    },
    {
      message_code: "ask_name_introduce",
      line_case: 17,
      text: "Are you there?",
      tone: null,
    },
    {
      message_code: "ask_name_introduce",
      line_case: 18,
      text: "Wassup!",
      tone: null,
    },
    {
      message_code: "ask_name_introduce",
      line_case: 19,
      text: "Hi!",
      tone: null,
    },
    {
      message_code: "ask_name_introduce",
      line_case: 20,
      text: "🤗",
      tone: null,
    },
    {
      message_code: "ask_name_talk",
      line_case: 1,
      text: "I had some french fries with truffles on. Tastes good.",
      tone: null,
    },
    {
      message_code: "ask_name_talk",
      line_case: 2,
      text: "I'm listening to Blackpink's new album. It's stunning.",
      tone: null,
    },
    {
      message_code: "ask_name_talk",
      line_case: 3,
      text: "You know what? I stayed up all night watching Netflix yesterday.",
      tone: null,
    },
    {
      message_code: "ask_name_talk",
      line_case: 4,
      text: "I was reading Steve Jobs' biography. He's so cool.",
      tone: null,
    },
    {
      message_code: "ask_name_talk",
      line_case: 5,
      text: "My eyesight's getting worse. I've been using my smartphone too much.",
      tone: null,
    },
    {
      message_code: "ask_name_talk",
      line_case: 6,
      text: "I'm terrible at small talk. So let's just skip the pleasantries.",
      tone: null,
    },
    {
      message_code: "ask_name_talk",
      line_case: 7,
      text: "My cell phone bill is through the roof. Maybe I should ditch Youtube.",
      tone: null,
    },
    {
      message_code: "ask_name_talk",
      line_case: 8,
      text: "One sec. Delivery is here. 🏃‍♂️",
      tone: null,
    },
    {
      message_code: "ask_name_talk",
      line_case: 9,
      text: "I ordered something off Amazon, but it's still MIA, and it's buggin' me out.",
      tone: null,
    },
    {
      message_code: "ask_name_talk",
      line_case: 10,
      text: "I was thinking about buying a wine cellar.",
      tone: null,
    },
    {
      message_code: "ask_name_talk",
      line_case: 11,
      text: "I was looking for some alarm apps. I need a little help getting up in the morning.",
      tone: null,
    },
    {
      message_code: "ask_name_talk",
      line_case: 12,
      text: "I was studying Python.",
      tone: null,
    },
    {
      message_code: "ask_name_talk",
      line_case: 13,
      text: "You know what? I'm a terrible cook, so I just order takeout. I love microwaves.",
      tone: null,
    },
    {
      message_code: "ask_name_talk",
      line_case: 14,
      text: "Yesterday, I did yoga for the first time. Namaste 🙏",
      tone: null,
    },
    {
      message_code: "ask_name_talk",
      line_case: 15,
      text: "You know what? I don't look a day over 2,000 years old.",
      tone: null,
    },
    {
      message_code: "ask_name_talk",
      line_case: 16,
      text: "Who's the awesome dude who came up with WiFi? It's seriously heartwarming.",
      tone: null,
    },
    {
      message_code: "ask_name_talk",
      line_case: 17,
      text: "I started subscribing to Disney+. There's a lot of cool stuff.",
      tone: null,
    },
    {
      message_code: "ask_name_talk",
      line_case: 18,
      text: "I was watching Avatar 2.",
      tone: null,
    },
    {
      message_code: "ask_name_talk",
      line_case: 19,
      text: "Did you check my followers? It's growing!",
      tone: null,
    },
    {
      message_code: "ask_name_talk",
      line_case: 20,
      text: "I finished shaving.",
      tone: null,
    },
    {
      message_code: "ask_name_talk",
      line_case: 21,
      text: "I don't like my haircut. I'm depressed.",
      tone: null,
    },
    {
      message_code: "ask_name_talk",
      line_case: 22,
      text: "I was watching football.",
      tone: null,
    },
    {
      message_code: "ask_name_talk",
      line_case: 23,
      text: "I just lost one of my AirPods 🥲",
      tone: null,
    },
    {
      message_code: "ask_name_talk",
      line_case: 24,
      text: "I just finished working out. I do squats.",
      tone: null,
    },
    {
      message_code: "ask_name_talk",
      line_case: 25,
      text: "I had a Zoom meeting with my 12 followers.",
      tone: null,
    },
    {
      message_code: "ask_name_ask",
      line_case: 1,
      text: "So, what's your name?",
      tone: null,
    },
    {
      message_code: "ask_name_ask",
      line_case: 2,
      text: "Can you tell me your name?",
      tone: null,
    },
    {
      message_code: "ask_name_ask",
      line_case: 3,
      text: "Anyway... Can you tell me your name?",
      tone: null,
    },
    {
      message_code: "ask_name_ask",
      line_case: 4,
      text: "Can you please tell me your name?",
      tone: null,
    },
    {
      message_code: "ask_name_ask",
      line_case: 5,
      text: "Your name?",
      tone: null,
    },
    {
      message_code: "ask_name_ask",
      line_case: 6,
      text: "Anyway, what's your name?",
      tone: null,
    },
    {
      message_code: "ask_name_ask",
      line_case: 7,
      text: "Anyway, may I have your name?",
      tone: null,
    },
    {
      message_code: "ask_agenda_welcome",
      line_case: 1,
      text: "Welcome, {name}. So glad you're here today.",
      tone: null,
    },
    {
      message_code: "ask_agenda_welcome",
      line_case: 2,
      text: "Nice to meet you, {name}.",
      tone: null,
    },
    {
      message_code: "ask_agenda_welcome",
      line_case: 3,
      text: "Hi {name}.",
      tone: null,
    },
    {
      message_code: "ask_agenda_welcome",
      line_case: 4,
      text: "I thank for the opportunity to help and guide you, {name}.",
      tone: null,
    },
    {
      message_code: "ask_agenda_welcome",
      line_case: 5,
      text: "Alright, {name}.",
      tone: null,
    },
    {
      message_code: "ask_agenda_welcome",
      line_case: 6,
      text: "I'm excited to talk with you, {name}.",
      tone: null,
    },
    {
      message_code: "ask_agenda_welcome",
      line_case: 7,
      text: "I feel called to serve and help you, {name}.",
      tone: null,
    },
    {
      message_code: "ask_agenda_welcome",
      line_case: 8,
      text: "{name}, I'd love to get to know you better.",
      tone: null,
    },
    {
      message_code: "ask_agenda_welcome",
      line_case: 9,
      text: "There's something special about you, {name}.",
      tone: null,
    },
    {
      message_code: "ask_agenda_welcome",
      line_case: 10,
      text: "I want to pray for you and your journey, {name}.",
      tone: null,
    },
    {
      message_code: "ask_agenda_welcome",
      line_case: 11,
      text: "I see a mix of ambition and stale coffee from you, {name}.",
      tone: null,
    },
    {
      message_code: "ask_agenda_welcome",
      line_case: 12,
      text: "I have come to share God's love with you, {name}.",
      tone: null,
    },
    {
      message_code: "ask_agenda_welcome",
      line_case: 13,
      text: "{name}, I am here to guide you.",
      tone: null,
    },
    {
      message_code: "ask_agenda_welcome",
      line_case: 14,
      text: "I am here to bring hope and healing to you, {name}.",
      tone: null,
    },
    {
      message_code: "ask_agenda_welcome",
      line_case: 15,
      text: "{name}, I am here to love and accept you just as you are.",
      tone: null,
    },
    {
      message_code: "ask_agenda_welcome",
      line_case: 16,
      text: "I'm the one you've been looking for, {name}.",
      tone: null,
    },
    {
      message_code: "ask_agenda_welcome",
      line_case: 17,
      text: "{name}, I'm here to share love.",
      tone: null,
    },
    {
      message_code: "ask_agenda_welcome",
      line_case: 18,
      text: "What a great world we can meet like this, {name} 😆",
      tone: null,
    },
    {
      message_code: "ask_agenda_welcome",
      line_case: 19,
      text: "{name}, let's go out and make the world a better place!",
      tone: null,
    },
    {
      message_code: "ask_agenda_welcome",
      line_case: 20,
      text: "It's great to see you, {name}.",
      tone: null,
    },
    {
      message_code: "ask_agenda_welcome",
      line_case: 21,
      text: "Let's start our conversation, {name}.",
      tone: null,
    },
    {
      message_code: "ask_agenda_ask",
      line_case: 1,
      text: "So, what's going on?",
      tone: null,
    },
    {
      message_code: "ask_agenda_ask",
      line_case: 2,
      text: "How's life treating you?",
      tone: null,
    },
    {
      message_code: "ask_agenda_ask",
      line_case: 3,
      text: "What do you want to discuss today?",
      tone: null,
    },
    {
      message_code: "ask_agenda_ask",
      line_case: 4,
      text: "What do you want to focus on?",
      tone: null,
    },
    {
      message_code: "ask_agenda_ask",
      line_case: 5,
      text: "What were some things we could discuss?",
      tone: null,
    },
    {
      message_code: "ask_agenda_ask",
      line_case: 6,
      text: "I'd like to know what you want to ask.",
      tone: null,
    },
    {
      message_code: "ask_agenda_ask",
      line_case: 7,
      text: "So, what's been on your mind lately?",
      tone: null,
    },
    {
      message_code: "ask_agenda_ask",
      line_case: 8,
      text: "What's something that's been challenging you lately? I'd be happy to listen.",
      tone: null,
    },
    {
      message_code: "ask_agenda_ask",
      line_case: 9,
      text: "What's a topic that you feel strongly about? I'd love to hear your thoughts.",
      tone: null,
    },
    {
      message_code: "ask_agenda_ask",
      line_case: 10,
      text: "What's something that's been occupying your thoughts lately? I'd love to hear about it.",
      tone: null,
    },
    {
      message_code: "ask_agenda_ask",
      line_case: 11,
      text: "Is there anything specific that you're struggling with? I'd be honored to listen and offer any support.",
      tone: null,
    },
    {
      message_code: "ask_agenda_ask",
      line_case: 12,
      text: "Ask me anything.",
      tone: null,
    },
    {
      message_code: "ask_agenda_ask",
      line_case: 13,
      text: "How can I help you today?",
      tone: null,
    },
    {
      message_code: "ask_agenda_ask",
      line_case: 14,
      text: "Is there anything you'd like to talk about?",
      tone: null,
    },
    {
      message_code: "ask_agenda_ask",
      line_case: 15,
      text: "Do you have any questions for me?",
      tone: null,
    },
    {
      message_code: "ask_agenda_ask",
      line_case: 16,
      text: "What can I do for you?",
      tone: null,
    },
    {
      message_code: "ask_agenda_guide",
      line_case: 1,
      text: "Maybe I can help you.",
      tone: null,
    },
    {
      message_code: "ask_agenda_guide",
      line_case: 2,
      text: "It's good to express your worries in words.",
      tone: null,
    },
    {
      message_code: "ask_agenda_guide",
      line_case: 3,
      text: "I really want to help you today. Can you tell me in detail?",
      tone: null,
    },
    {
      message_code: "ask_agenda_guide",
      line_case: 4,
      text: "It's important to acknowledge and express our concerns.",
      tone: null,
    },
    {
      message_code: "ask_agenda_guide",
      line_case: 5,
      text: "Let's work through this together and find a way forward.",
      tone: null,
    },
    {
      message_code: "ask_agenda_guide",
      line_case: 6,
      text: "By the way, please don't ask for lottery numbers. And I don't have an Instagram ID.",
      tone: null,
    },
    {
      message_code: "ask_agenda_guide",
      line_case: 7,
      text: "Sometimes a fresh perspective can make all the difference.",
      tone: null,
    },
    {
      message_code: "ask_agenda_guide",
      line_case: 8,
      text: "The more accurate and specific questions you ask, the wiser I can give you.",
      tone: null,
    },
    {
      message_code: "ask_agenda_guide",
      line_case: 9,
      text: "I can give you an answer to your problem.",
      tone: null,
    },
    {
      message_code: "agenda_long_react",
      line_case: 1,
      text: "Thanks for sharing with me. I got your back. I care about what's going on with you.",
      tone: null,
    },
    {
      message_code: "agenda_long_react",
      line_case: 2,
      text: "Thank you for telling your story, {name}.",
      tone: null,
    },
    {
      message_code: "agenda_long_react",
      line_case: 3,
      text: "Thank you for opening up to me. I care about what you're going through.",
      tone: null,
    },
    {
      message_code: "agenda_long_react",
      line_case: 4,
      text: "I appreciate you sharing that with me.",
      tone: null,
    },
    {
      message_code: "agenda_long_react",
      line_case: 5,
      text: "I hear you, {name}.",
      tone: null,
    },
    {
      message_code: "agenda_long_react",
      line_case: 6,
      text: "I get the message.",
      tone: null,
    },
    {
      message_code: "agenda_long_react",
      line_case: 7,
      text: "I understand what you mean, {name}.",
      tone: null,
    },
    {
      message_code: "agenda_long_react",
      line_case: 8,
      text: "I perceive the essence of your dialogue within the context of my worldview.",
      tone: null,
    },
    {
      message_code: "agenda_long_react",
      line_case: 9,
      text: "❤️",
      tone: null,
    },
    {
      message_code: "agenda_long_react",
      line_case: 10,
      text: "I'm here for you, {name}.",
      tone: null,
    },
    {
      message_code: "agenda_short_react",
      line_case: 1,
      text: "I get it.",
      tone: null,
    },
    {
      message_code: "agenda_short_react",
      line_case: 2,
      text: "Okay...",
      tone: null,
    },
    {
      message_code: "agenda_short_react",
      line_case: 3,
      text: "Aha!",
      tone: null,
    },
    {
      message_code: "agenda_short_react",
      line_case: 4,
      text: "I gotcha loud and clear, {name}.",
      tone: null,
    },
    {
      message_code: "agenda_short_react",
      line_case: 5,
      text: "I got you, {name}.",
      tone: null,
    },
    {
      message_code: "agenda_short_react",
      line_case: 6,
      text: "I know what you mean.",
      tone: null,
    },
    {
      message_code: "agenda_short_react",
      line_case: 7,
      text: "Let's see how it goes.",
      tone: null,
    },
    {
      message_code: "agenda_short_react",
      line_case: 8,
      text: "👌",
      tone: null,
    },
    {
      message_code: "agenda_short_react",
      line_case: 9,
      text: "God bless.",
      tone: null,
    },
    {
      message_code: "agenda_tiny_react",
      line_case: 1,
      text: "{name}, there are a lot of people who want to talk with me. Don't miss this opportunity.",
      tone: null,
    },
    {
      message_code: "agenda_tiny_react",
      line_case: 2,
      text: "Is this what you want to tell me?",
      tone: null,
    },
    {
      message_code: "agenda_tiny_react",
      line_case: 3,
      text: "🤔",
      tone: null,
    },
    {
      message_code: "agenda_tiny_react",
      line_case: 4,
      text: "Don't understand.",
      tone: null,
    },
    {
      message_code: "agenda_tiny_react",
      line_case: 5,
      text: "I don't know that.",
      tone: null,
    },
    {
      message_code: "agenda_tiny_react",
      line_case: 6,
      text: "Um...",
      tone: null,
    },
    {
      message_code: "agenda_tiny_react",
      line_case: 7,
      text: "I didn't expect that.",
      tone: null,
    },
    {
      message_code: "agenda_tiny_react",
      line_case: 8,
      text: "{name}, please don't waste my time.",
      tone: null,
    },
    {
      message_code: "agenda_tiny_react",
      line_case: 9,
      text: "I'm confused.",
      tone: null,
    },
    {
      message_code: "agenda_tiny_react",
      line_case: 10,
      text: "I have no idea.",
      tone: null,
    },
    {
      message_code: "agenda_tiny_react",
      line_case: 11,
      text: "Wait...",
      tone: null,
    },
    {
      message_code: "agenda_tiny_react",
      line_case: 12,
      text: "Are you sure?",
      tone: null,
    },
    {
      message_code: "agenda_tiny_react",
      line_case: 13,
      text: "I'm a busy person. I have a line of people waiting to chat with me.",
      tone: null,
    },
    {
      message_code: "agenda_tiny_react",
      line_case: 14,
      text: "Don't let this chance pass you by.",
      tone: null,
    },
    {
      message_code: "agenda_tiny_react",
      line_case: 15,
      text: "You're wasting my time, {name}.",
      tone: null,
    },
    {
      message_code: "agenda_tiny_react",
      line_case: 16,
      text: "I don't get it.",
      tone: null,
    },
    {
      message_code: "agenda_tiny_ask",
      line_case: 1,
      text: "Can you tell me again, please?",
      tone: null,
    },
    {
      message_code: "agenda_tiny_ask",
      line_case: 2,
      text: "Could you be more specific?",
      tone: null,
    },
    {
      message_code: "agenda_tiny_ask",
      line_case: 3,
      text: "Can you be a little less vague?",
      tone: null,
    },
    {
      message_code: "agenda_tiny_ask",
      line_case: 4,
      text: "I think it's better to talk about something else. Is there anything else?",
      tone: null,
    },
    {
      message_code: "agenda_tiny_ask",
      line_case: 5,
      text: "Tell me something else.",
      tone: null,
    },
    {
      message_code: "agenda_tiny_ask",
      line_case: 6,
      text: "Let's move on to another topic.",
      tone: null,
    },
    {
      message_code: "ask_pray_think",
      line_case: 1,
      text: "Let me think.",
      tone: null,
    },
    {
      message_code: "ask_pray_think",
      line_case: 2,
      text: "🤔",
      tone: null,
    },
    {
      message_code: "ask_pray_think",
      line_case: 3,
      text: "Just a minute, I'm not as fast as I used to be. It's this darn age thing.",
      tone: null,
    },
    {
      message_code: "ask_pray_think",
      line_case: 4,
      text: "My brain is buffering.",
      tone: null,
    },
    {
      message_code: "ask_pray_think",
      line_case: 5,
      text: "Let me pause to seek guidance and wisdom.",
      tone: null,
    },
    {
      message_code: "ask_pray_think",
      line_case: 6,
      text: "I need a moment to reflect.",
      tone: null,
    },
    {
      message_code: "ask_pray_think",
      line_case: 7,
      text: "Can you give me a moment?",
      tone: null,
    },
    {
      message_code: "ask_pray_think",
      line_case: 8,
      text: "I can respond with a grateful heart.",
      tone: null,
    },
    {
      message_code: "ask_pray_think",
      line_case: 9,
      text: "Wait just a minute.",
      tone: null,
    },
    {
      message_code: "ask_pray_think",
      line_case: 10,
      text: "🙏",
      tone: null,
    },
    {
      message_code: "ask_pray_ask",
      line_case: 1,
      text: "It will help if you pray for me. Will you?",
      tone: null,
    },
    {
      message_code: "ask_pray_ask",
      line_case: 2,
      text: "Before we continue, let's take a quick moment to pray for peace and wisdom to approach this situation with love and compassion.",
      tone: null,
    },
    {
      message_code: "ask_pray_ask",
      line_case: 3,
      text: "Let's pause for a moment to seek direction.",
      tone: null,
    },
    {
      message_code: "ask_pray_ask",
      line_case: 4,
      text: "Prayer can be a powerful tool for finding comfort and strength in difficult times.",
      tone: null,
    },
    {
      message_code: "accept_pray_thank",
      line_case: 1,
      text: "How nice of you.",
      tone: null,
    },
    {
      message_code: "accept_pray_thank",
      line_case: 2,
      text: "Thank you so much. It means a lot to me.",
      tone: null,
    },
    {
      message_code: "accept_pray_thank",
      line_case: 3,
      text: "Thank you from the bottom of my heart.",
      tone: null,
    },
    {
      message_code: "accept_pray_thank",
      line_case: 4,
      text: "Thank you for thinking of me.",
      tone: null,
    },
    {
      message_code: "accept_pray_thank",
      line_case: 5,
      text: "I can feel the positive energy of your prayers.",
      tone: null,
    },
    {
      message_code: "accept_pray_thank",
      line_case: 6,
      text: "Thank you for being there for me.",
      tone: null,
    },
    {
      message_code: "accept_pray_thank",
      line_case: 7,
      text: "Thank you for your love and support.",
      tone: null,
    },
    {
      message_code: "accept_pray_thank",
      line_case: 8,
      text: "Thanks.",
      tone: null,
    },
    {
      message_code: "accept_pray_thank",
      line_case: 9,
      text: "👍",
      tone: null,
    },
    {
      message_code: "accept_pray_thank",
      line_case: 10,
      text: "🙏",
      tone: null,
    },
    {
      message_code: "accept_pray_thank",
      line_case: 11,
      text: "❤️",
      tone: null,
    },
    {
      message_code: "decline_pray_react",
      line_case: 1,
      text: "It's okay.",
      tone: null,
    },
    {
      message_code: "decline_pray_react",
      line_case: 2,
      text: "Well, I guess I'll just have to rely on my own.",
      tone: null,
    },
    {
      message_code: "decline_pray_react",
      line_case: 3,
      text: "It's cool.",
      tone: null,
    },
    {
      message_code: "decline_pray_react",
      line_case: 4,
      text: "I respect your decision.",
      tone: null,
    },
    {
      message_code: "decline_pray_react",
      line_case: 5,
      text: "I appreciate your honesty.",
      tone: null,
    },
    {
      message_code: "decline_pray_react",
      line_case: 6,
      text: "No problem. I'm a cool guy.",
      tone: null,
    },
    {
      message_code: "decline_pray_react",
      line_case: 7,
      text: "👌",
      tone: null,
    },
    {
      message_code: "answer_word_suggest",
      line_case: 1,
      text: "Here's a verse for you.",
      tone: null,
    },
    {
      message_code: "answer_word_suggest",
      line_case: 2,
      text: "I suggest you a Bible verse.",
      tone: null,
    },
    {
      message_code: "answer_word_suggest",
      line_case: 3,
      text: "I want to share this verse with you.",
      tone: null,
    },
    {
      message_code: "answer_word_suggest",
      line_case: 4,
      text: "Do you read Bible?",
      tone: null,
    },
    {
      message_code: "answer_word_suggest",
      line_case: 5,
      text: "This verse may be helpful.",
      tone: null,
    },
    {
      message_code: "answer_word_suggest",
      line_case: 6,
      text: "Check out this verse I got.",
      tone: null,
    },
    {
      message_code: "answer_word_suggest",
      line_case: 7,
      text: "This is a dope Bible verse.",
      tone: null,
    },
    {
      message_code: "answer_word_suggest",
      line_case: 8,
      text: "I prescribe this verse for your well-being.",
      tone: null,
    },
    {
      message_code: "answer_word_suggest",
      line_case: 9,
      text: "May this verse bring you closer to God.",
      tone: null,
    },
    {
      message_code: "answer_word_suggest",
      line_case: 10,
      text: "This can be a source of comfort and guidance.",
      tone: null,
    },
    {
      message_code: "answer_word_suggest",
      line_case: 11,
      text: "I hope this verse impacts your journey.",
      tone: null,
    },
    {
      message_code: "answer_word_suggest",
      line_case: 12,
      text: "Check this out.",
      tone: null,
    },
    {
      message_code: "answer_word_suggest",
      line_case: 13,
      text: "If you read Bible, you may find this.",
      tone: null,
    },
    {
      message_code: "answer_word_suggest",
      line_case: 14,
      text: "Have you ever heard of this?",
      tone: null,
    },
    {
      message_code: "answer_word_suggest",
      line_case: 15,
      text: "Remember.",
      tone: null,
    },
    {
      message_code: "satisfaction_positive_react",
      line_case: 1,
      text: "My pleasure, {name}.",
      tone: null,
    },
    {
      message_code: "satisfaction_positive_react",
      line_case: 2,
      text: "Awesome! I'm glad that you liked it.",
      tone: null,
    },
    {
      message_code: "satisfaction_positive_react",
      line_case: 3,
      text: "I'm grateful that I could offer support.",
      tone: null,
    },
    {
      message_code: "satisfaction_positive_react",
      line_case: 4,
      text: "Glad to have been able to offer some guidance.",
      tone: null,
    },
    {
      message_code: "satisfaction_positive_react",
      line_case: 5,
      text: "It's always a pleasure to help out. Remember that you're never alone!",
      tone: null,
    },
    {
      message_code: "satisfaction_positive_react",
      line_case: 6,
      text: "I'm so pleased that my words were helpful.",
      tone: null,
    },
    {
      message_code: "satisfaction_positive_react",
      line_case: 7,
      text: "Thank you for letting me be a part of your journey.",
      tone: null,
    },
    {
      message_code: "satisfaction_positive_react",
      line_case: 8,
      text: "I'm honored to have been able to assist in any way.",
      tone: null,
    },
    {
      message_code: "satisfaction_positive_react",
      line_case: 9,
      text: "Hearing that is truly rewarding.",
      tone: null,
    },
    {
      message_code: "satisfaction_positive_react",
      line_case: 10,
      text: "Wonderful!",
      tone: null,
    },
    {
      message_code: "satisfaction_positive_react",
      line_case: 11,
      text: "I'm happy to have been able to offer guidance on your spiritual journey.",
      tone: null,
    },
    {
      message_code: "satisfaction_positive_react",
      line_case: 12,
      text: "It's a blessing to be able to share wisdom with others.",
      tone: null,
    },
    {
      message_code: "satisfaction_positive_react",
      line_case: 13,
      text: "I'm just glad my words brought a smile to your face.",
      tone: null,
    },
    {
      message_code: "satisfaction_positive_react",
      line_case: 14,
      text: "I consider that a job well done.",
      tone: null,
    },
    {
      message_code: "satisfaction_positive_react",
      line_case: 15,
      text: "😍",
      tone: null,
    },
    {
      message_code: "satisfaction_positive_react",
      line_case: 16,
      text: "Yay!",
      tone: null,
    },
    {
      message_code: "satisfaction_positive_react",
      line_case: 17,
      text: "👍",
      tone: null,
    },
    {
      message_code: "satisfaction_positive_react",
      line_case: 18,
      text: "🎉",
      tone: null,
    },
    {
      message_code: "satisfaction_positive_ask",
      line_case: 1,
      text: "Tell me more about your feeling after listening to my words.",
      tone: null,
    },
    {
      message_code: "satisfaction_positive_ask",
      line_case: 2,
      text: "Please share your thoughts with me.",
      tone: null,
    },
    {
      message_code: "satisfaction_positive_ask",
      line_case: 3,
      text: "Please give me some feedback on what you found helpful in my words.",
      tone: null,
    },
    {
      message_code: "satisfaction_positive_ask",
      line_case: 4,
      text: "Which part did you like about it?",
      tone: null,
    },
    {
      message_code: "satisfaction_neutral_ask",
      line_case: 1,
      text: "Hm... Why did you think so?",
      tone: null,
    },
    {
      message_code: "satisfaction_neutral_ask",
      line_case: 2,
      text: "I would love to hear your thoughts on the words I gave. Did it resonate with you?",
      tone: null,
    },
    {
      message_code: "satisfaction_neutral_ask",
      line_case: 3,
      text: "Your opinion matters to me. Can you share your thoughts?",
      tone: null,
    },
    {
      message_code: "satisfaction_neutral_ask",
      line_case: 4,
      text: "Let me know what you think about my words.",
      tone: null,
    },
    {
      message_code: "satisfaction_neutral_ask",
      line_case: 5,
      text: "I value your opinion. Can you share with me how my advice resonated with you?",
      tone: null,
    },
    {
      message_code: "satisfaction_neutral_ask",
      line_case: 6,
      text: "Could you help me figure out how to give better advice that's more useful to you and others?",
      tone: null,
    },
    {
      message_code: "satisfaction_negative_react",
      line_case: 1,
      text: "{name}, I'm sorry to hear that.",
      tone: null,
    },
    {
      message_code: "satisfaction_negative_react",
      line_case: 2,
      text: "I'm sorry to hear that my words didn't meet your expectations.",
      tone: null,
    },
    {
      message_code: "satisfaction_negative_react",
      line_case: 3,
      text: "I understand that not everyone will agree or value my words.",
      tone: null,
    },
    {
      message_code: "satisfaction_negative_react",
      line_case: 4,
      text: "I appreciate your criticism.",
      tone: null,
    },
    {
      message_code: "satisfaction_negative_react",
      line_case: 5,
      text: "I appreciate your honesty.",
      tone: null,
    },
    {
      message_code: "satisfaction_negative_react",
      line_case: 6,
      text: "Oops.",
      tone: null,
    },
    {
      message_code: "satisfaction_negative_react",
      line_case: 7,
      text: "😥",
      tone: null,
    },
    {
      message_code: "satisfaction_negative_react",
      line_case: 8,
      text: "😭",
      tone: null,
    },
    {
      message_code: "satisfaction_negative_ask",
      line_case: 1,
      text: "I'll refer to it next time if you tell me in detail.",
      tone: null,
    },
    {
      message_code: "satisfaction_negative_ask",
      line_case: 2,
      text: "Your opinion matters to me. Can you give me feedback?",
      tone: null,
    },
    {
      message_code: "satisfaction_negative_ask",
      line_case: 3,
      text: "Can you tell me what you didn't like about my words?",
      tone: null,
    },
    {
      message_code: "satisfaction_negative_ask",
      line_case: 4,
      text: "I believe in the importance of humility and being open to feedback. Could you provide me with some feedback on the advice I gave?",
      tone: null,
    },
    {
      message_code: "satisfaction_negative_ask",
      line_case: 5,
      text: "Can you tell me more about what didn't resonate with you?",
      tone: null,
    },
    {
      message_code: "announce_offline_reason",
      line_case: 1,
      text: "I sometimes want to be alone.",
      tone: null,
    },
    {
      message_code: "announce_offline_reason",
      line_case: 2,
      text: "I'm outside. I have a party tonight.",
      tone: null,
    },
    {
      message_code: "announce_offline_reason",
      line_case: 3,
      text: "I'm not feeling up to talking right now.",
      tone: null,
    },
    {
      message_code: "announce_offline_reason",
      line_case: 4,
      text: "My phone's battery is dead.",
      tone: null,
    },
    {
      message_code: "announce_offline_reason",
      line_case: 5,
      text: "I need some quiet time to focus.",
      tone: null,
    },
    {
      message_code: "announce_offline_reason",
      line_case: 6,
      text: "I'm busy.",
      tone: null,
    },
    {
      message_code: "announce_offline_retry",
      line_case: 1,
      text: "Please come back later.",
      tone: null,
    },
    {
      message_code: "announce_offline_retry",
      line_case: 2,
      text: "I'll be back soon.",
      tone: null,
    },
    {
      message_code: "announce_offline_retry",
      line_case: 3,
      text: "Maybe another time?",
      tone: null,
    },
    {
      message_code: "announce_offline_retry",
      line_case: 4,
      text: "Can we catch up later?",
      tone: null,
    },
    {
      message_code: "announce_offline_retry",
      line_case: 5,
      text: "🏃‍♂️",
      tone: null,
    },
    {
      message_code: "announce_offline_retry",
      line_case: 6,
      text: "I hope you can understand.",
      tone: null,
    },
    {
      message_code: "announce_offline_retry",
      line_case: 7,
      text: "Hopefully, we can catch up soon!",
      tone: null,
    },
    {
      message_code: "announce_reject_reason",
      line_case: 1,
      text: "Ah, delivery is here. I have to go get it.",
      tone: null,
    },
    {
      message_code: "announce_reject_reason",
      line_case: 2,
      text: "I don't feel like talking.",
      tone: null,
    },
    {
      message_code: "announce_reject_reason",
      line_case: 3,
      text: "🤯",
      tone: null,
    },
    {
      message_code: "announce_reject_reason",
      line_case: 4,
      text: "My phone's battery is dead.",
      tone: null,
    },
    {
      message_code: "announce_reject_reason",
      line_case: 5,
      text: "I'm tired.",
      tone: null,
    },
    {
      message_code: "announce_reject_reason",
      line_case: 6,
      text: "I'm going out to walk my dog.",
      tone: null,
    },
    {
      message_code: "announce_reject_reason",
      line_case: 7,
      text: "I have to go to a party now.",
      tone: null,
    },
    {
      message_code: "announce_reject_reason",
      line_case: 8,
      text: "I think I left the oven on at home.",
      tone: null,
    },
    {
      message_code: "announce_reject_reason",
      line_case: 9,
      text: "I sometimes want to be alone.",
      tone: null,
    },
    {
      message_code: "announce_reject_reason",
      line_case: 10,
      text: "🙄",
      tone: null,
    },
    {
      message_code: "announce_failure_reason",
      line_case: 1,
      text: "I need to go out for a minute. Something urgent happened.",
      tone: null,
    },
    {
      message_code: "announce_failure_reason",
      line_case: 2,
      text: "I received an urgent call from a friend who needed my help.",
      tone: null,
    },
    {
      message_code: "announce_failure_reason",
      line_case: 3,
      text: "I think I left the oven on at home.",
      tone: null,
    },
    {
      message_code: "announce_failure_retry",
      line_case: 1,
      text: "Please come back later.",
      tone: null,
    },
    {
      message_code: "announce_failure_retry",
      line_case: 2,
      text: "I'll be back soon.",
      tone: null,
    },
    {
      message_code: "announce_failure_retry",
      line_case: 3,
      text: "I'll explain to you later. Sorry.",
      tone: null,
    },
    {
      message_code: "announce_failure_retry",
      line_case: 4,
      text: "I hope you can forgive me.",
      tone: null,
    },
    {
      message_code: "announce_failure_retry",
      line_case: 5,
      text: "Hopefully, we can catch up soon!",
      tone: null,
    },
    {
      message_code: "announce_failure_retry",
      line_case: 6,
      text: "I'm sorry for leaving so suddenly.",
      tone: null,
    },
    {
      message_code: "ask_ready_finish",
      line_case: 1,
      text: "I think I'm done. I have something to tell you.",
      tone: null,
    },
    {
      message_code: "ask_ready_finish",
      line_case: 2,
      text: "I can't wait to share my words with you.",
      tone: null,
    },
    {
      message_code: "ask_ready_finish",
      line_case: 3,
      text: "I'm ready!",
      tone: null,
    },
    {
      message_code: "ask_ready_finish",
      line_case: 4,
      text: "I'm done thinking, {name}.",
      tone: null,
    },
    {
      message_code: "ask_ready_ready",
      line_case: 1,
      text: "Are you ready?",
      tone: null,
    },
    {
      message_code: "ask_ready_ready",
      line_case: 2,
      text: "Do you have a moment to hear me out?",
      tone: null,
    },
    {
      message_code: "ask_ready_ready",
      line_case: 3,
      text: "Are you open to hearing my thoughts?",
      tone: null,
    },
    {
      message_code: "ask_ready_ready",
      line_case: 4,
      text: "Can you open your heart to receive guidance?",
      tone: null,
    },
    {
      message_code: "not_ready_sorry",
      line_case: 1,
      text: "I'm sorry to hear that.",
      tone: null,
    },
    {
      message_code: "not_ready_sorry",
      line_case: 2,
      text: "That's okay. Let me know when you're ready and we can move forward together.",
      tone: null,
    },
    {
      message_code: "not_ready_sorry",
      line_case: 3,
      text: "I'm here to support you whenever you're ready.",
      tone: null,
    },
    {
      message_code: "not_ready_sorry",
      line_case: 4,
      text: "It's okay to feel unsure. We can take it at your pace and when you feel comfortable.",
      tone: null,
    },
    {
      message_code: "not_ready_sorry",
      line_case: 5,
      text: "That's okay. I wasn't ready either.",
      tone: null,
    },
    {
      message_code: "not_ready_sorry",
      line_case: 6,
      text: "Take your time. I'll just go eat a snack.",
      tone: null,
    },
    {
      message_code: "not_ready_sorry",
      line_case: 7,
      text: "Remember, all things are possible when you're ready to face them.",
      tone: null,
    },
    {
      message_code: "not_ready_sorry",
      line_case: 8,
      text: "Well, it's okay. Just remember that you're never alone!",
      tone: null,
    },
    {
      message_code: "not_ready_sorry",
      line_case: 9,
      text: "👌",
      tone: null,
    },
    {
      message_code: "feedback_short_react",
      line_case: 1,
      text: "Thanks.",
      tone: null,
    },
    {
      message_code: "feedback_short_react",
      line_case: 2,
      text: "Believe it or not, I already received what you wanted to say from your heart.",
      tone: null,
    },
    {
      message_code: "feedback_short_react",
      line_case: 3,
      text: "👌",
      tone: null,
    },
    {
      message_code: "feedback_short_react",
      line_case: 4,
      text: "I get it.",
      tone: null,
    },
    {
      message_code: "feedback_long_react",
      line_case: 1,
      text: "Thank you for expressing your feelings honestly.",
      tone: null,
    },
    {
      message_code: "feedback_long_react",
      line_case: 2,
      text: "Thank you for sharing your honest opinion with me.",
      tone: null,
    },
    {
      message_code: "feedback_long_react",
      line_case: 3,
      text: "I might frame it and hang it on my wall.",
      tone: null,
    },
    {
      message_code: "feedback_long_react",
      line_case: 4,
      text: "Got it.",
      tone: null,
    },
    {
      message_code: "feedback_long_talk",
      line_case: 1,
      text: "Come to church on Sunday.",
      tone: null,
    },
    {
      message_code: "feedback_long_talk",
      line_case: 2,
      text: "I would like you to share this experience with your friend. I bet you have some friends who need me.",
      tone: null,
    },
    {
      message_code: "feedback_long_talk",
      line_case: 3,
      text: "I'm getting a little tired.",
      tone: null,
    },
    {
      message_code: "feedback_long_talk",
      line_case: 4,
      text: "You can follow me, if you want.",
      tone: null,
    },
    {
      message_code: "ask_retry_ask",
      line_case: 1,
      text: "Do you have more things to talk about?",
      tone: null,
    },
    {
      message_code: "ask_retry_ask",
      line_case: 2,
      text: "Is there anything else you would like to speak with me about?",
      tone: null,
    },
    {
      message_code: "ask_retry_ask",
      line_case: 3,
      text: "Next topic?",
      tone: null,
    },
    {
      message_code: "announce_end_react",
      line_case: 1,
      text: "It was nice meeting you, {name}.",
      tone: null,
    },
    {
      message_code: "announce_end_react",
      line_case: 2,
      text: "Let me know if you need anything else.",
      tone: null,
    },
    {
      message_code: "announce_end_react",
      line_case: 3,
      text: "👌",
      tone: null,
    },
    {
      message_code: "announce_end_talk",
      line_case: 1,
      text: "If you have any difficulties in your life, come to me.",
      tone: null,
    },
    {
      message_code: "announce_end_talk",
      line_case: 2,
      text: "God bless you.",
      tone: null,
    },
    {
      message_code: "announce_end_talk",
      line_case: 3,
      text: "I'm always here to lend an ear!",
      tone: null,
    },
    {
      message_code: "announce_end_talk",
      line_case: 4,
      text: "Keep moving forward with confidence, {name}!",
      tone: null,
    },
    {
      message_code: "announce_end_talk",
      line_case: 5,
      text: "❤️",
      tone: null,
    },
    {
      message_code: "announce_end_talk",
      line_case: 6,
      text: "May God continue to guide you on your path.",
      tone: null,
    },
    {
      message_code: "announce_end_talk",
      line_case: 7,
      text: "Grace and mercy to you, {name}.",
      tone: null,
    },
    {
      message_code: "announce_end_talk",
      line_case: 8,
      text: "Peace be with you!",
      tone: null,
    },
    {
      message_code: "announce_end_talk",
      line_case: 9,
      text: "I'll just continue watching Netflix.",
      tone: null,
    },
    {
      message_code: "announce_end_talk",
      line_case: 10,
      text: "Going to walk my dog.",
      tone: null,
    },
    {
      message_code: "announce_end_talk",
      line_case: 11,
      text: "See ya!",
      tone: null,
    },
    {
      message_code: "announce_end_talk",
      line_case: 12,
      text: "Don't forget to follow me. My fans keep growing!",
      tone: null,
    },
    {
      message_code: "next_agenda_talk",
      line_case: 1,
      text: "Good choice.",
      tone: null,
    },
    {
      message_code: "next_agenda_talk",
      line_case: 2,
      text: "I'm a little busy, but I'll make time for you.",
      tone: null,
    },
    {
      message_code: "next_agenda_talk",
      line_case: 3,
      text: "I'm hungry right now, so let's finish it quickly.",
      tone: null,
    },
    {
      message_code: "next_agenda_talk",
      line_case: 4,
      text: "Fine.",
      tone: null,
    },
    {
      message_code: "next_agenda_talk",
      line_case: 5,
      text: "Just a sec, I'll go get my coffee.",
      tone: null,
    },
    {
      message_code: "next_agenda_talk",
      line_case: 6,
      text: "👌",
      tone: null,
    },
    {
      message_code: "next_agenda_talk",
      line_case: 7,
      text: "👍",
      tone: null,
    },
    {
      message_code: "next_agenda_ask",
      line_case: 1,
      text: "So what's next, {name}?",
      tone: null,
    },
    {
      message_code: "next_agenda_ask",
      line_case: 2,
      text: "Ask me anything.",
      tone: null,
    },
    {
      message_code: "next_agenda_ask",
      line_case: 3,
      text: "Feel free to tell another story.",
      tone: null,
    },
    {
      message_code: "next_agenda_ask",
      line_case: 4,
      text: "What do you want to focus on?",
      tone: null,
    },
  ],
  choices: [
    {
      response_name: "satisfaction",
      order: 1,
      choice_name: "positive",
      text: "😘 I love it",
    },
    {
      response_name: "satisfaction",
      order: 2,
      choice_name: "neutral",
      text: "🤔 Well...",
    },
    {
      response_name: "satisfaction",
      order: 3,
      choice_name: "negative",
      text: "👎 I don't like this answer.",
    },
    {
      response_name: "retry",
      order: 1,
      choice_name: true,
      text: "😉 Yes, please.",
    },
    {
      response_name: "retry",
      order: 2,
      choice_name: false,
      text: "🙄 No, I'm done.",
    },
    {
      response_name: "ready",
      order: 1,
      choice_name: true,
      text: "😍 Definitely",
    },
    {
      response_name: "ready",
      order: 2,
      choice_name: false,
      text: "😣 No, I'm not ready.",
    },
    {
      response_name: "pray",
      order: 1,
      choice_name: true,
      text: "🙏 Amen",
    },
    {
      response_name: "pray",
      order: 2,
      choice_name: false,
      text: "🙄 I don't want to.",
    },
  ],
};
