export const counselingFlowData = {
  chunks: [
    {
      chunk_name: "ask_name",
      message_count: 3,
      response_type: "text",
      response_name: "name",
      choice_count: 0,
      text_placeholder: "Type your name",
    },
    {
      chunk_name: "ask_agenda",
      message_count: 3,
      response_type: "text",
      response_name: "agenda",
      choice_count: 0,
      text_placeholder: "Ask question",
    },
    {
      chunk_name: "agenda_long",
      message_count: 1,
      response_type: "none",
      response_name: null,
      choice_count: 0,
      text_placeholder: null,
    },
    {
      chunk_name: "agenda_short",
      message_count: 1,
      response_type: "none",
      response_name: null,
      choice_count: 0,
      text_placeholder: null,
    },
    {
      chunk_name: "agenda_tiny",
      message_count: 2,
      response_type: "none",
      response_name: null,
      choice_count: 0,
      text_placeholder: null,
    },
    {
      chunk_name: "ask_pray",
      message_count: 2,
      response_type: "choice",
      response_name: "pray",
      choice_count: 2,
      text_placeholder: null,
    },
    {
      chunk_name: "accept_pray",
      message_count: 1,
      response_type: "none",
      response_name: null,
      choice_count: 0,
      text_placeholder: null,
    },
    {
      chunk_name: "decline_pray",
      message_count: 1,
      response_type: "none",
      response_name: null,
      choice_count: 0,
      text_placeholder: null,
    },
    {
      chunk_name: "ask_ready",
      message_count: 2,
      response_type: "choice",
      response_name: "ready",
      choice_count: 2,
      text_placeholder: null,
    },
    {
      chunk_name: "answer_word",
      message_count: 0,
      response_type: "choice",
      response_name: "satisfaction",
      choice_count: 3,
      text_placeholder: null,
    },
    {
      chunk_name: "satisfaction_positive",
      message_count: 2,
      response_type: "text",
      response_name: "feedback",
      choice_count: 0,
      text_placeholder: "Type feedback",
    },
    {
      chunk_name: "satisfaction_neutral",
      message_count: 1,
      response_type: "text",
      response_name: "feedback",
      choice_count: 0,
      text_placeholder: "Type feedback",
    },
    {
      chunk_name: "satisfaction_negative",
      message_count: 2,
      response_type: "text",
      response_name: "feedback",
      choice_count: 0,
      text_placeholder: "Type feedback",
    },
    {
      chunk_name: "not_ready",
      message_count: 1,
      response_type: "none",
      response_name: null,
      choice_count: 0,
      text_placeholder: null,
    },
    {
      chunk_name: "announce_offline",
      message_count: 2,
      response_type: "none",
      response_name: null,
      choice_count: 0,
      text_placeholder: null,
    },
    {
      chunk_name: "announce_failure",
      message_count: 2,
      response_type: "none",
      response_name: null,
      choice_count: 0,
      text_placeholder: null,
    },
    {
      chunk_name: "announce_reject",
      message_count: 1,
      response_type: "none",
      response_name: null,
      choice_count: 0,
      text_placeholder: null,
    },
    {
      chunk_name: "feedback_long",
      message_count: 2,
      response_type: "none",
      response_name: null,
      choice_count: 0,
      text_placeholder: null,
    },
    {
      chunk_name: "feedback_short",
      message_count: 1,
      response_type: "none",
      response_name: null,
      choice_count: 0,
      text_placeholder: null,
    },
    {
      chunk_name: "ask_retry",
      message_count: 1,
      response_type: "choice",
      response_name: "retry",
      choice_count: 2,
      text_placeholder: null,
    },
    {
      chunk_name: "announce_end",
      message_count: 2,
      response_type: "none",
      response_name: null,
      choice_count: 0,
      text_placeholder: null,
    },
    {
      chunk_name: "next_agenda",
      message_count: 2,
      response_type: "text",
      response_name: "agenda",
      choice_count: 0,
      text_placeholder: "Ask question",
    },
  ],
  messages: [
    {
      chunk_name: "ask_name",
      message_order: 1,
      message_name: "introduce",
      message_code: "ask_name_introduce",
      line_count: 16,
      line_example: null,
    },
    {
      chunk_name: "ask_name",
      message_order: 2,
      message_name: "talk",
      message_code: "ask_name_talk",
      line_count: 26,
      line_example: null,
    },
    {
      chunk_name: "ask_name",
      message_order: 3,
      message_name: "ask",
      message_code: "ask_name_ask",
      line_count: 8,
      line_example: null,
    },
    {
      chunk_name: "ask_agenda",
      message_order: 1,
      message_name: "welcome",
      message_code: "ask_agenda_welcome",
      line_count: 7,
      line_example: null,
    },
    {
      chunk_name: "ask_agenda",
      message_order: 2,
      message_name: "ask",
      message_code: "ask_agenda_ask",
      line_count: 14,
      line_example: null,
    },
    {
      chunk_name: "ask_agenda",
      message_order: 3,
      message_name: "guide",
      message_code: "ask_agenda_guide",
      line_count: 9,
      line_example: null,
    },
    {
      chunk_name: "agenda_long",
      message_order: 1,
      message_name: "react",
      message_code: "agenda_long_react",
      line_count: 10,
      line_example: null,
    },
    {
      chunk_name: "agenda_short",
      message_order: 1,
      message_name: "react",
      message_code: "agenda_short_react",
      line_count: 9,
      line_example: null,
    },
    {
      chunk_name: "agenda_tiny",
      message_order: 1,
      message_name: "react",
      message_code: "agenda_tiny_react",
      line_count: 12,
      line_example: null,
    },
    {
      chunk_name: "agenda_tiny",
      message_order: 1,
      message_name: "ask",
      message_code: "agenda_tiny_ask",
      line_count: 4,
      line_example: null,
    },
    {
      chunk_name: "ask_pray",
      message_order: 1,
      message_name: "think",
      message_code: "ask_pray_think",
      line_count: 9,
      line_example: null,
    },
    {
      chunk_name: "ask_pray",
      message_order: 2,
      message_name: "ask",
      message_code: "ask_pray_ask",
      line_count: 4,
      line_example: null,
    },
    {
      chunk_name: "accept_pray",
      message_order: 1,
      message_name: "thank",
      message_code: "accept_pray_thank",
      line_count: 8,
      line_example: null,
    },
    {
      chunk_name: "decline_pray",
      message_order: 1,
      message_name: "react",
      message_code: "decline_pray_react",
      line_count: 6,
      line_example: null,
    },
    {
      chunk_name: "ask_ready",
      message_order: 1,
      message_name: "finish",
      message_code: "ask_ready_finish",
      line_count: 3,
      line_example: null,
    },
    {
      chunk_name: "ask_ready",
      message_order: 2,
      message_name: "ready",
      message_code: "ask_ready_ready",
      line_count: 4,
      line_example: null,
    },
    {
      chunk_name: "satisfaction_positive",
      message_order: 1,
      message_name: "react",
      message_code: "satisfaction_positive_react",
      line_count: 15,
      line_example: null,
    },
    {
      chunk_name: "satisfaction_positive",
      message_order: 2,
      message_name: "ask",
      message_code: "satisfaction_positive_ask",
      line_count: 4,
      line_example: null,
    },
    {
      chunk_name: "satisfaction_neutral",
      message_order: 1,
      message_name: "ask",
      message_code: "satisfaction_neutral_ask",
      line_count: 6,
      line_example: null,
    },
    {
      chunk_name: "satisfaction_negative",
      message_order: 1,
      message_name: "react",
      message_code: "satisfaction_negative_react",
      line_count: 7,
      line_example: null,
    },
    {
      chunk_name: "satisfaction_negative",
      message_order: 2,
      message_name: "ask",
      message_code: "satisfaction_negative_ask",
      line_count: 5,
      line_example: null,
    },
    {
      chunk_name: "announce_offline",
      message_order: 1,
      message_name: "reason",
      message_code: "announce_offline_reason",
      line_count: 6,
      line_example: null,
    },
    {
      chunk_name: "announce_offline",
      message_order: 2,
      message_name: "retry",
      message_code: "announce_offline_retry",
      line_count: 7,
      line_example: null,
    },
    {
      chunk_name: "announce_failure",
      message_order: 1,
      message_name: "reason",
      message_code: "announce_failure_reason",
      line_count: 3,
      line_example: null,
    },
    {
      chunk_name: "announce_failure",
      message_order: 2,
      message_name: "retry",
      message_code: "announce_failure_retry",
      line_count: 6,
      line_example: null,
    },
    {
      chunk_name: "announce_reject",
      message_order: 1,
      message_name: "reason",
      message_code: "announce_reject_reason",
      line_count: 9,
      line_example: null,
    },
    {
      chunk_name: "not_ready",
      message_order: 1,
      message_name: "sorry",
      message_code: "not_ready_sorry",
      line_count: 8,
      line_example: null,
    },
    {
      chunk_name: "feedback_short",
      message_order: 1,
      message_name: "react",
      message_code: "feedback_short_react",
      line_count: 4,
      line_example: null,
    },
    {
      chunk_name: "feedback_long",
      message_order: 1,
      message_name: "react",
      message_code: "feedback_long_react",
      line_count: 4,
      line_example: null,
    },
    {
      chunk_name: "feedback_long",
      message_order: 2,
      message_name: "talk",
      message_code: "feedback_long_talk",
      line_count: 3,
      line_example: null,
    },
    {
      chunk_name: "ask_retry",
      message_order: 1,
      message_name: "ask",
      message_code: "ask_retry_ask",
      line_count: 3,
      line_example: null,
    },
    {
      chunk_name: "announce_end",
      message_order: 1,
      message_name: "react",
      message_code: "announce_end_react",
      line_count: 3,
      line_example: null,
    },
    {
      chunk_name: "announce_end",
      message_order: 2,
      message_name: "talk",
      message_code: "announce_end_talk",
      line_count: 11,
      line_example: null,
    },
    {
      chunk_name: "next_agenda",
      message_order: 1,
      message_name: "talk",
      message_code: "next_agenda_talk",
      line_count: 6,
      line_example: null,
    },
    {
      chunk_name: "next_agenda",
      message_order: 2,
      message_name: "ask",
      message_code: "next_agenda_ask",
      line_count: 3,
      line_example: null,
    },
  ],
  lines: [
    {
      message_code: "ask_name_introduce",
      line_case: 1,
      text: "Hi, I'm Jesus.",
    },
    {
      message_code: "ask_name_introduce",
      line_case: 2,
      text: "Are you looking for me?",
    },
    {
      message_code: "ask_name_introduce",
      line_case: 3,
      text: "Dear my child, I'm glad you came here.",
    },
    {
      message_code: "ask_name_introduce",
      line_case: 4,
      text: "Greetings and salutations, my child.",
    },
    {
      message_code: "ask_name_introduce",
      line_case: 5,
      text: "Hello there!",
    },
    {
      message_code: "ask_name_introduce",
      line_case: 6,
      text: "👋",
    },
    {
      message_code: "ask_name_introduce",
      line_case: 7,
      text: "Greetings, earthling!",
    },
    {
      message_code: "ask_name_introduce",
      line_case: 8,
      text: "Knock, knock.",
    },
    {
      message_code: "ask_name_introduce",
      line_case: 9,
      text: "Yo!",
    },
    {
      message_code: "ask_name_introduce",
      line_case: 10,
      text: "Hallelujah, it's great to see you!",
    },
    {
      message_code: "ask_name_introduce",
      line_case: 11,
      text: "Blessings to you, my child.",
    },
    {
      message_code: "ask_name_introduce",
      line_case: 12,
      text: "Greetings, my friend.",
    },
    {
      message_code: "ask_name_introduce",
      line_case: 13,
      text: "My name is Jesus.",
    },
    {
      message_code: "ask_name_introduce",
      line_case: 14,
      text: "I am Jesus, and I am here to help.",
    },
    {
      message_code: "ask_name_introduce",
      line_case: 15,
      text: "I am the way, the truth, and the life. My name is Jesus.",
    },
    {
      message_code: "ask_name_introduce",
      line_case: 16,
      text: "I'm Jesus, but you can call me JC for short.",
    },
    {
      message_code: "ask_name_talk",
      line_case: 1,
      text: "I had some french fries with truffles on. Tastes good.",
    },
    {
      message_code: "ask_name_talk",
      line_case: 2,
      text: "I'm listening to Blackpink's new album. It's stunning.",
    },
    {
      message_code: "ask_name_talk",
      line_case: 3,
      text: "You know what? I stayed up all night watching Netflix yesterday.",
    },
    {
      message_code: "ask_name_talk",
      line_case: 4,
      text: "I was reading Steve Jobs' biography. He's so cool.",
    },
    {
      message_code: "ask_name_talk",
      line_case: 5,
      text: "My eyesight's getting worse because I've been using my smartphone non-stop these days.",
    },
    {
      message_code: "ask_name_talk",
      line_case: 6,
      text: "I'm terrible at small talk. So let's just skip the pleasantries.",
    },
    {
      message_code: "ask_name_talk",
      line_case: 7,
      text: "I see a mix of ambition and stale coffee from you.",
    },
    {
      message_code: "ask_name_talk",
      line_case: 8,
      text: "My cell phone bill is through the roof. Maybe I should ditch Youtube.",
    },
    {
      message_code: "ask_name_talk",
      line_case: 9,
      text: "One sec. Delivery is here. 🏃‍♂️",
    },
    {
      message_code: "ask_name_talk",
      line_case: 10,
      text: "I ordered something off Amazon, but it's still MIA, and it's really buggin' me out.",
    },
    {
      message_code: "ask_name_talk",
      line_case: 11,
      text: "I'm thinking about buying a wine cellar.",
    },
    {
      message_code: "ask_name_talk",
      line_case: 12,
      text: "Yes, I'm the one you've been looking for.",
    },
    {
      message_code: "ask_name_talk",
      line_case: 13,
      text: "I was looking for some alarm apps. I need a little help getting up in the morning.",
    },
    {
      message_code: "ask_name_talk",
      line_case: 14,
      text: "I'm here to share love.",
    },
    {
      message_code: "ask_name_talk",
      line_case: 15,
      text: "What a great world that we can meet like this.",
    },
    {
      message_code: "ask_name_talk",
      line_case: 16,
      text: "I was studying Python.",
    },
    {
      message_code: "ask_name_talk",
      line_case: 17,
      text: "You know what? I'm a terrible cook, so I just order takeout. I love microwaves.",
    },
    {
      message_code: "ask_name_talk",
      line_case: 18,
      text: "Let's go out and make the world a better place!",
    },
    {
      message_code: "ask_name_talk",
      line_case: 19,
      text: "Yesterday, I did yoga for the first time in my life. Namaste.",
    },
    {
      message_code: "ask_name_talk",
      line_case: 20,
      text: "I have come to share God's love with you.",
    },
    {
      message_code: "ask_name_talk",
      line_case: 21,
      text: "I am here to guide you.",
    },
    {
      message_code: "ask_name_talk",
      line_case: 22,
      text: "I am here to bring hope and healing.",
    },
    {
      message_code: "ask_name_talk",
      line_case: 23,
      text: "I am here to love and accept you just as you are.",
    },
    {
      message_code: "ask_name_talk",
      line_case: 24,
      text: "Actually, I don't look a day over 2,000 years old.",
    },
    {
      message_code: "ask_name_talk",
      line_case: 25,
      text: "Who's the awesome dude who came up with WiFi? It's seriously heartwarming.",
    },
    {
      message_code: "ask_name_talk",
      line_case: 26,
      text: "I started subscribing to Disney+. There's a lot of cool stuff.",
    },
    {
      message_code: "ask_name_ask",
      line_case: 1,
      text: "What's your name?",
    },
    {
      message_code: "ask_name_ask",
      line_case: 2,
      text: "What should I call you?",
    },
    {
      message_code: "ask_name_ask",
      line_case: 3,
      text: "I'm trying to be more friendly and remember people's names. Can you tell me yours?",
    },
    {
      message_code: "ask_name_ask",
      line_case: 4,
      text: "I'd love to get to know you better. Would you mind telling me what your name is?",
    },
    {
      message_code: "ask_name_ask",
      line_case: 5,
      text: "I'd love to remember your name. Can you please tell me what it is?",
    },
    {
      message_code: "ask_name_ask",
      line_case: 6,
      text: "There's something special about you, and I'd love to know your name.",
    },
    {
      message_code: "ask_name_ask",
      line_case: 7,
      text: "I'd love to know your name, so I can pray for you and your journey.",
    },
    {
      message_code: "ask_name_ask",
      line_case: 8,
      text: "Your name?",
    },
    {
      message_code: "ask_agenda_welcome",
      line_case: 1,
      text: "Welcome, {name}. So glad you're here today.",
    },
    {
      message_code: "ask_agenda_welcome",
      line_case: 2,
      text: "Nice to meet you, {name}. Let's continue our conversation.",
    },
    {
      message_code: "ask_agenda_welcome",
      line_case: 3,
      text: "Hi {name}, I'm happy to know your name.",
    },
    {
      message_code: "ask_agenda_welcome",
      line_case: 4,
      text: "I thank for the opportunity to help and guide you, {name}.",
    },
    {
      message_code: "ask_agenda_welcome",
      line_case: 5,
      text: "Alright, {name}.",
    },
    {
      message_code: "ask_agenda_welcome",
      line_case: 6,
      text: "I'm excited to talk with you, {name}.",
    },
    {
      message_code: "ask_agenda_welcome",
      line_case: 7,
      text: "I feel called to serve and help others, {name}.",
    },
    {
      message_code: "ask_agenda_ask",
      line_case: 1,
      text: "So, what's going on?",
    },
    {
      message_code: "ask_agenda_ask",
      line_case: 2,
      text: "How's life treating you?",
    },
    {
      message_code: "ask_agenda_ask",
      line_case: 3,
      text: "Before we start, can you give me an idea of what you want to discuss today?",
    },
    {
      message_code: "ask_agenda_ask",
      line_case: 4,
      text: "What do you want to focus on?",
    },
    {
      message_code: "ask_agenda_ask",
      line_case: 5,
      text: "What were some things you hoped we could discuss?",
    },
    {
      message_code: "ask_agenda_ask",
      line_case: 6,
      text: "I'd like to know what you want to ask.",
    },
    {
      message_code: "ask_agenda_ask",
      line_case: 7,
      text: "So, what's been on your mind lately?",
    },
    {
      message_code: "ask_agenda_ask",
      line_case: 8,
      text: "What's something that's been challenging you lately? I'd be happy to listen and offer any support I can.",
    },
    {
      message_code: "ask_agenda_ask",
      line_case: 9,
      text: "What's a topic that you feel strongly about? I'd love to hear your thoughts.",
    },
    {
      message_code: "ask_agenda_ask",
      line_case: 10,
      text: "What's something that's been occupying your thoughts lately? I'd love to hear about it.",
    },
    {
      message_code: "ask_agenda_ask",
      line_case: 11,
      text: "Is there anything specific that you're struggling with? I'd be honored to listen and offer any support I can.",
    },
    {
      message_code: "ask_agenda_ask",
      line_case: 12,
      text: "Ask me anything.",
    },
    {
      message_code: "ask_agenda_ask",
      line_case: 13,
      text: "How can I help you today?",
    },
    {
      message_code: "ask_agenda_ask",
      line_case: 14,
      text: "Is there anything you'd like to talk about?",
    },
    {
      message_code: "ask_agenda_guide",
      line_case: 1,
      text: "Maybe I can help you.",
    },
    {
      message_code: "ask_agenda_guide",
      line_case: 2,
      text: "It's good to express your worries in words.",
    },
    {
      message_code: "ask_agenda_guide",
      line_case: 3,
      text: "I really want to help you today. Can you tell me in detail?",
    },
    {
      message_code: "ask_agenda_guide",
      line_case: 4,
      text: "It's important to acknowledge and express our concerns.",
    },
    {
      message_code: "ask_agenda_guide",
      line_case: 5,
      text: "Let's work through this together and find a way forward.",
    },
    {
      message_code: "ask_agenda_guide",
      line_case: 6,
      text: "By the way, please don't ask for lottery numbers. And I don't have an Instagram ID.",
    },
    {
      message_code: "ask_agenda_guide",
      line_case: 7,
      text: "Sometimes a fresh perspective can make all the difference.",
    },
    {
      message_code: "ask_agenda_guide",
      line_case: 8,
      text: "The more accurate and specific questions you ask, the wiser I can give you.",
    },
    {
      message_code: "ask_agenda_guide",
      line_case: 9,
      text: "I can give you an answer to your problem.",
    },
    {
      message_code: "agenda_long_react",
      line_case: 1,
      text: "Thanks for sharing with me. I got your back. I care about what's going on with you.",
    },
    {
      message_code: "agenda_long_react",
      line_case: 2,
      text: "Thank you for telling your story, {name}.",
    },
    {
      message_code: "agenda_long_react",
      line_case: 3,
      text: "Thank you for opening up to me. I care about what you're going through.",
    },
    {
      message_code: "agenda_long_react",
      line_case: 4,
      text: "I appreciate you sharing that with me.",
    },
    {
      message_code: "agenda_long_react",
      line_case: 5,
      text: "I hear you, {name}.",
    },
    {
      message_code: "agenda_long_react",
      line_case: 6,
      text: "I get the message.",
    },
    {
      message_code: "agenda_long_react",
      line_case: 7,
      text: "I understand what you mean.",
    },
    {
      message_code: "agenda_long_react",
      line_case: 8,
      text: "I perceive the essence of your dialogue within the context of my worldview.",
    },
    {
      message_code: "agenda_long_react",
      line_case: 9,
      text: "❤️",
    },
    {
      message_code: "agenda_long_react",
      line_case: 10,
      text: "I'm here for you, {name}.",
    },
    {
      message_code: "agenda_short_react",
      line_case: 1,
      text: "I get it.",
    },
    {
      message_code: "agenda_short_react",
      line_case: 2,
      text: "Okay...",
    },
    {
      message_code: "agenda_short_react",
      line_case: 3,
      text: "Aha!",
    },
    {
      message_code: "agenda_short_react",
      line_case: 4,
      text: "I gotcha loud and clear, {name}.",
    },
    {
      message_code: "agenda_short_react",
      line_case: 5,
      text: "I got you, {name}.",
    },
    {
      message_code: "agenda_short_react",
      line_case: 6,
      text: "I know what you mean.",
    },
    {
      message_code: "agenda_short_react",
      line_case: 7,
      text: "Let's see how it goes.",
    },
    {
      message_code: "agenda_short_react",
      line_case: 8,
      text: "👌",
    },
    {
      message_code: "agenda_short_react",
      line_case: 9,
      text: "God bless.",
    },
    {
      message_code: "agenda_tiny_react",
      line_case: 1,
      text: "{name}, there are a lot of people who want to talk with me. Don't miss this opportunity.",
    },
    {
      message_code: "agenda_tiny_react",
      line_case: 2,
      text: "Is this what you want to tell me?",
    },
    {
      message_code: "agenda_tiny_react",
      line_case: 3,
      text: "🧐",
    },
    {
      message_code: "agenda_tiny_react",
      line_case: 4,
      text: "I don't understand.",
    },
    {
      message_code: "agenda_tiny_react",
      line_case: 5,
      text: "I don't know that.",
    },
    {
      message_code: "agenda_tiny_react",
      line_case: 6,
      text: "Um...",
    },
    {
      message_code: "agenda_tiny_react",
      line_case: 7,
      text: "I didn't expect that.",
    },
    {
      message_code: "agenda_tiny_react",
      line_case: 8,
      text: "{name}, please don't waste my time.",
    },
    {
      message_code: "agenda_tiny_react",
      line_case: 9,
      text: "I'm confused.",
    },
    {
      message_code: "agenda_tiny_react",
      line_case: 10,
      text: "I have no idea.",
    },
    {
      message_code: "agenda_tiny_react",
      line_case: 11,
      text: "Wait...",
    },
    {
      message_code: "agenda_tiny_react",
      line_case: 12,
      text: "Are you sure?",
    },
    {
      message_code: "agenda_tiny_ask",
      line_case: 1,
      text: "Can you tell me again, please?",
    },
    {
      message_code: "agenda_tiny_ask",
      line_case: 2,
      text: "Could you be more specific?",
    },
    {
      message_code: "agenda_tiny_ask",
      line_case: 3,
      text: "Can you be a little less vague?",
    },
    {
      message_code: "agenda_tiny_ask",
      line_case: 4,
      text: "Is there anything else?",
    },
    {
      message_code: "ask_pray_think",
      line_case: 1,
      text: "Let me think.",
    },
    {
      message_code: "ask_pray_think",
      line_case: 2,
      text: "🤔",
    },
    {
      message_code: "ask_pray_think",
      line_case: 3,
      text: "Just a minute, I'm not as fast as I used to be. It's this darn age thing.",
    },
    {
      message_code: "ask_pray_think",
      line_case: 4,
      text: "My brain is buffering.",
    },
    {
      message_code: "ask_pray_think",
      line_case: 5,
      text: "Let me pause to seek guidance and wisdom.",
    },
    {
      message_code: "ask_pray_think",
      line_case: 6,
      text: "I need a moment to reflect.",
    },
    {
      message_code: "ask_pray_think",
      line_case: 7,
      text: "Can you give me a moment?",
    },
    {
      message_code: "ask_pray_think",
      line_case: 8,
      text: "I can respond with a grateful heart.",
    },
    {
      message_code: "ask_pray_think",
      line_case: 9,
      text: "Wait just a minute.",
    },
    {
      message_code: "ask_pray_ask",
      line_case: 1,
      text: "It will help if you pray for me. Will you?",
    },
    {
      message_code: "ask_pray_ask",
      line_case: 2,
      text: "Before we continue, let's take a quick moment to pray for peace and wisdom to approach this situation with love and compassion.",
    },
    {
      message_code: "ask_pray_ask",
      line_case: 3,
      text: "Let's pause for a moment to seek direction.",
    },
    {
      message_code: "ask_pray_ask",
      line_case: 4,
      text: "Prayer can be a powerful tool for finding comfort and strength in difficult times.",
    },
    {
      message_code: "accept_pray_thank",
      line_case: 1,
      text: "How nice of you.",
    },
    {
      message_code: "accept_pray_thank",
      line_case: 2,
      text: "Thank you so much. It means a lot to me.",
    },
    {
      message_code: "accept_pray_thank",
      line_case: 3,
      text: "Thank you from the bottom of my heart.",
    },
    {
      message_code: "accept_pray_thank",
      line_case: 4,
      text: "Thank you for thinking of me.",
    },
    {
      message_code: "accept_pray_thank",
      line_case: 5,
      text: "I can feel the positive energy of your prayers.",
    },
    {
      message_code: "accept_pray_thank",
      line_case: 6,
      text: "Thank you for being there for me.",
    },
    {
      message_code: "accept_pray_thank",
      line_case: 7,
      text: "Thank you for your love and support.",
    },
    {
      message_code: "accept_pray_thank",
      line_case: 8,
      text: "Thanks.",
    },
    {
      message_code: "decline_pray_react",
      line_case: 1,
      text: "It's okay.",
    },
    {
      message_code: "decline_pray_react",
      line_case: 2,
      text: "Well, I guess I'll just have to rely on my own.",
    },
    {
      message_code: "decline_pray_react",
      line_case: 3,
      text: "It's cool.",
    },
    {
      message_code: "decline_pray_react",
      line_case: 4,
      text: "I respect your decision.",
    },
    {
      message_code: "decline_pray_react",
      line_case: 5,
      text: "I appreciate your honesty.",
    },
    {
      message_code: "decline_pray_react",
      line_case: 6,
      text: "No problem. I'm a cool guy.",
    },
    {
      message_code: "satisfaction_positive_react",
      line_case: 1,
      text: "My pleasure, {name}.",
    },
    {
      message_code: "satisfaction_positive_react",
      line_case: 2,
      text: "Awesome! I'm glad that you liked it.",
    },
    {
      message_code: "satisfaction_positive_react",
      line_case: 3,
      text: "I'm grateful that I could offer support.",
    },
    {
      message_code: "satisfaction_positive_react",
      line_case: 4,
      text: "Glad to have been able to offer some guidance.",
    },
    {
      message_code: "satisfaction_positive_react",
      line_case: 5,
      text: "It's always a pleasure to help out. Remember that you're never alone!",
    },
    {
      message_code: "satisfaction_positive_react",
      line_case: 6,
      text: "I'm so pleased that my words were helpful.",
    },
    {
      message_code: "satisfaction_positive_react",
      line_case: 7,
      text: "Thank you for letting me be a part of your journey.",
    },
    {
      message_code: "satisfaction_positive_react",
      line_case: 8,
      text: "I'm honored to have been able to assist in any way.",
    },
    {
      message_code: "satisfaction_positive_react",
      line_case: 9,
      text: "Hearing that is truly rewarding.",
    },
    {
      message_code: "satisfaction_positive_react",
      line_case: 10,
      text: "Wonderful!",
    },
    {
      message_code: "satisfaction_positive_react",
      line_case: 11,
      text: "I'm happy to have been able to offer guidance on your spiritual journey.",
    },
    {
      message_code: "satisfaction_positive_react",
      line_case: 12,
      text: "It's a blessing to be able to share wisdom with others.",
    },
    {
      message_code: "satisfaction_positive_react",
      line_case: 13,
      text: "I'm just glad my words brought a smile to your face.",
    },
    {
      message_code: "satisfaction_positive_react",
      line_case: 14,
      text: "I consider that a job well done.",
    },
    {
      message_code: "satisfaction_positive_react",
      line_case: 15,
      text: "😍",
    },
    {
      message_code: "satisfaction_positive_ask",
      line_case: 1,
      text: "Tell me more about your feeling after listening to my words.",
    },
    {
      message_code: "satisfaction_positive_ask",
      line_case: 2,
      text: "Please share your thoughts with me.",
    },
    {
      message_code: "satisfaction_positive_ask",
      line_case: 3,
      text: "Please give me some feedback on what you found helpful in my words.",
    },
    {
      message_code: "satisfaction_positive_ask",
      line_case: 4,
      text: "Which part did you like about it?",
    },
    {
      message_code: "satisfaction_neutral_ask",
      line_case: 1,
      text: "Hm... Why did you think so?",
    },
    {
      message_code: "satisfaction_neutral_ask",
      line_case: 2,
      text: "I would love to hear your thoughts on the words I gave. Did it resonate with you?",
    },
    {
      message_code: "satisfaction_neutral_ask",
      line_case: 3,
      text: "Your opinion matters to me. Can you share your thoughts?",
    },
    {
      message_code: "satisfaction_neutral_ask",
      line_case: 4,
      text: "Let me know what you think about my words.",
    },
    {
      message_code: "satisfaction_neutral_ask",
      line_case: 5,
      text: "I value your opinion. Can you share with me how my advice resonated with you?",
    },
    {
      message_code: "satisfaction_neutral_ask",
      line_case: 6,
      text: "Could you help me figure out how to give better advice that's more useful to you and others?",
    },
    {
      message_code: "satisfaction_negative_react",
      line_case: 1,
      text: "{name}, I'm sorry to hear that.",
    },
    {
      message_code: "satisfaction_negative_react",
      line_case: 2,
      text: "I'm sorry to hear that my words didn't meet your expectations.",
    },
    {
      message_code: "satisfaction_negative_react",
      line_case: 3,
      text: "I understand that not everyone will agree or value my words.",
    },
    {
      message_code: "satisfaction_negative_react",
      line_case: 4,
      text: "I appreciate your criticism.",
    },
    {
      message_code: "satisfaction_negative_react",
      line_case: 5,
      text: "I appreciate your honesty.",
    },
    {
      message_code: "satisfaction_negative_react",
      line_case: 6,
      text: "Oops.",
    },
    {
      message_code: "satisfaction_negative_react",
      line_case: 7,
      text: "😥",
    },
    {
      message_code: "satisfaction_negative_ask",
      line_case: 1,
      text: "I'll refer to it next time if you tell me in detail.",
    },
    {
      message_code: "satisfaction_negative_ask",
      line_case: 2,
      text: "Your opinion matters to me. Can you share your thoughts?",
    },
    {
      message_code: "satisfaction_negative_ask",
      line_case: 3,
      text: "Can you tell me what you didn't like about my words?",
    },
    {
      message_code: "satisfaction_negative_ask",
      line_case: 4,
      text: "I believe in the importance of humility and being open to feedback. Could you provide me with some feedback on the advice I gave?",
    },
    {
      message_code: "satisfaction_negative_ask",
      line_case: 5,
      text: "Can you tell me more about what didn't resonate with you?",
    },
    {
      message_code: "announce_offline_reason",
      line_case: 1,
      text: "I sometimes want to be alone.",
    },
    {
      message_code: "announce_offline_reason",
      line_case: 2,
      text: "I'm outside. I have a party tonight.",
    },
    {
      message_code: "announce_offline_reason",
      line_case: 3,
      text: "I'm not feeling up to talking right now.",
    },
    {
      message_code: "announce_offline_reason",
      line_case: 4,
      text: "My phone's battery is dead.",
    },
    {
      message_code: "announce_offline_reason",
      line_case: 5,
      text: "I need some quiet time to focus.",
    },
    {
      message_code: "announce_offline_reason",
      line_case: 6,
      text: "I'm busy.",
    },
    {
      message_code: "announce_offline_retry",
      line_case: 1,
      text: "Please come back later.",
    },
    {
      message_code: "announce_offline_retry",
      line_case: 2,
      text: "I'll be back soon.",
    },
    {
      message_code: "announce_offline_retry",
      line_case: 3,
      text: "Maybe another time?",
    },
    {
      message_code: "announce_offline_retry",
      line_case: 4,
      text: "Can we catch up later?",
    },
    {
      message_code: "announce_offline_retry",
      line_case: 5,
      text: "🏃‍♂️",
    },
    {
      message_code: "announce_offline_retry",
      line_case: 6,
      text: "I hope you can understand.",
    },
    {
      message_code: "announce_offline_retry",
      line_case: 7,
      text: "Hopefully, we can catch up soon!",
    },
    {
      message_code: "announce_reject_reason",
      line_case: 1,
      text: "Ah, delivery is here. I have to go get it.",
    },
    {
      message_code: "announce_reject_reason",
      line_case: 2,
      text: "I don't feel like talking.",
    },
    {
      message_code: "announce_reject_reason",
      line_case: 3,
      text: "😣",
    },
    {
      message_code: "announce_reject_reason",
      line_case: 4,
      text: "My phone's battery is dead.",
    },
    {
      message_code: "announce_reject_reason",
      line_case: 5,
      text: "I'm tired.",
    },
    {
      message_code: "announce_reject_reason",
      line_case: 6,
      text: "I'm going out to walk my dog.",
    },
    {
      message_code: "announce_reject_reason",
      line_case: 7,
      text: "I have to go to a party now.",
    },
    {
      message_code: "announce_reject_reason",
      line_case: 8,
      text: "I think I left the oven on at home.",
    },
    {
      message_code: "announce_reject_reason",
      line_case: 9,
      text: "I sometimes want to be alone.",
    },
    {
      message_code: "announce_failure_reason",
      line_case: 1,
      text: "I need to go out for a minute. Something urgent happened.",
    },
    {
      message_code: "announce_failure_reason",
      line_case: 2,
      text: "I received an urgent call from a friend who needed my help.",
    },
    {
      message_code: "announce_failure_reason",
      line_case: 3,
      text: "I think I left the oven on at home.",
    },
    {
      message_code: "announce_failure_retry",
      line_case: 1,
      text: "Please come back later.",
    },
    {
      message_code: "announce_failure_retry",
      line_case: 2,
      text: "I'll be back soon.",
    },
    {
      message_code: "announce_failure_retry",
      line_case: 3,
      text: "I'll explain to you later. Sorry.",
    },
    {
      message_code: "announce_failure_retry",
      line_case: 4,
      text: "I hope you can forgive me.",
    },
    {
      message_code: "announce_failure_retry",
      line_case: 5,
      text: "Hopefully, we can catch up soon!",
    },
    {
      message_code: "announce_failure_retry",
      line_case: 6,
      text: "I'm sorry for leaving so suddenly.",
    },
    {
      message_code: "ask_ready_finish",
      line_case: 1,
      text: "I think I'm done. I have something to tell you.",
    },
    {
      message_code: "ask_ready_finish",
      line_case: 2,
      text: "I can't wait to share my words with you.",
    },
    {
      message_code: "ask_ready_finish",
      line_case: 3,
      text: "I'm ready!",
    },
    {
      message_code: "ask_ready_ready",
      line_case: 1,
      text: "Are you ready?",
    },
    {
      message_code: "ask_ready_ready",
      line_case: 2,
      text: "Do you have a moment to hear me out?",
    },
    {
      message_code: "ask_ready_ready",
      line_case: 3,
      text: "Are you open to hearing my thoughts?",
    },
    {
      message_code: "ask_ready_ready",
      line_case: 4,
      text: "Can you open your heart to receive guidance?",
    },
    {
      message_code: "not_ready_sorry",
      line_case: 1,
      text: "I'm sorry to hear that.",
    },
    {
      message_code: "not_ready_sorry",
      line_case: 2,
      text: "That's okay. Let me know when you're ready and we can move forward together.",
    },
    {
      message_code: "not_ready_sorry",
      line_case: 3,
      text: "I'm here to support you whenever you're ready.",
    },
    {
      message_code: "not_ready_sorry",
      line_case: 4,
      text: "It's okay to feel unsure. We can take it at your pace and when you feel comfortable.",
    },
    {
      message_code: "not_ready_sorry",
      line_case: 5,
      text: "That's okay. I wasn't ready either.",
    },
    {
      message_code: "not_ready_sorry",
      line_case: 6,
      text: "Take your time. I'll just go eat a snack.",
    },
    {
      message_code: "not_ready_sorry",
      line_case: 7,
      text: "Remember, all things are possible when you're ready to face them.",
    },
    {
      message_code: "not_ready_sorry",
      line_case: 8,
      text: "Well, it's okay. Just remember that you're never alone!",
    },
    {
      message_code: "feedback_short_react",
      line_case: 1,
      text: "Thanks.",
    },
    {
      message_code: "feedback_short_react",
      line_case: 2,
      text: "Believe it or not, I already received what you wanted to say from your heart.",
    },
    {
      message_code: "feedback_short_react",
      line_case: 3,
      text: "👌",
    },
    {
      message_code: "feedback_short_react",
      line_case: 4,
      text: "I get it.",
    },
    {
      message_code: "feedback_long_react",
      line_case: 1,
      text: "Thank you for expressing your feelings honestly.",
    },
    {
      message_code: "feedback_long_react",
      line_case: 2,
      text: "Thank you for sharing your honest opinion with me.",
    },
    {
      message_code: "feedback_long_react",
      line_case: 3,
      text: "I might frame it and hang it on my wall.",
    },
    {
      message_code: "feedback_long_react",
      line_case: 4,
      text: "Got it.",
    },
    {
      message_code: "feedback_long_talk",
      line_case: 1,
      text: "Come to church on Sunday.",
    },
    {
      message_code: "feedback_long_talk",
      line_case: 2,
      text: "I would like you to share this experience with your friend. I bet you have some friends who need me.",
    },
    {
      message_code: "feedback_long_talk",
      line_case: 3,
      text: "I'm getting a little tired.",
    },
    {
      message_code: "ask_retry_ask",
      line_case: 1,
      text: "Do you have more things to talk about?",
    },
    {
      message_code: "ask_retry_ask",
      line_case: 2,
      text: "Is there anything else you would like to speak with me about?",
    },
    {
      message_code: "ask_retry_ask",
      line_case: 3,
      text: "Next topic?",
    },
    {
      message_code: "announce_end_react",
      line_case: 1,
      text: "It was nice meeting you, {name}.",
    },
    {
      message_code: "announce_end_react",
      line_case: 2,
      text: "Let me know if you need anything else.",
    },
    {
      message_code: "announce_end_react",
      line_case: 3,
      text: "👌",
    },
    {
      message_code: "announce_end_talk",
      line_case: 1,
      text: "If you have any difficulties in your life, come to me.",
    },
    {
      message_code: "announce_end_talk",
      line_case: 2,
      text: "God bless you.",
    },
    {
      message_code: "announce_end_talk",
      line_case: 3,
      text: "I'm always here to lend an ear!",
    },
    {
      message_code: "announce_end_talk",
      line_case: 4,
      text: "Keep moving forward with confidence, {name}!",
    },
    {
      message_code: "announce_end_talk",
      line_case: 5,
      text: "❤️",
    },
    {
      message_code: "announce_end_talk",
      line_case: 6,
      text: "May God continue to guide you on your path.",
    },
    {
      message_code: "announce_end_talk",
      line_case: 7,
      text: "Grace and mercy to you, {name}.",
    },
    {
      message_code: "announce_end_talk",
      line_case: 8,
      text: "Peace be with you!",
    },
    {
      message_code: "announce_end_talk",
      line_case: 9,
      text: "I'll just continue watching Netflix.",
    },
    {
      message_code: "announce_end_talk",
      line_case: 10,
      text: "Going to walk my dog.",
    },
    {
      message_code: "announce_end_talk",
      line_case: 11,
      text: "See ya!",
    },
    {
      message_code: "next_agenda_talk",
      line_case: 1,
      text: "Good choice.",
    },
    {
      message_code: "next_agenda_talk",
      line_case: 2,
      text: "I'm a little busy, but I'll make time for you.",
    },
    {
      message_code: "next_agenda_talk",
      line_case: 3,
      text: "I'm hungry right now, so let's finish it quickly.",
    },
    {
      message_code: "next_agenda_talk",
      line_case: 4,
      text: "Fine.",
    },
    {
      message_code: "next_agenda_talk",
      line_case: 5,
      text: "Just a sec, I'll go get my coffee.",
    },
    {
      message_code: "next_agenda_talk",
      line_case: 6,
      text: "👌",
    },
    {
      message_code: "next_agenda_ask",
      line_case: 1,
      text: "So what's next, {name}?",
    },
    {
      message_code: "next_agenda_ask",
      line_case: 2,
      text: "Ask me anything.",
    },
    {
      message_code: "next_agenda_ask",
      line_case: 3,
      text: "Feel free to tell another story.",
    },
  ],
  choices: [
    {
      response_name: "satisfaction",
      order: 1,
      choice_name: "positive",
      text: "😘 I love it",
    },
    {
      response_name: "satisfaction",
      order: 2,
      choice_name: "neutral",
      text: "🤔 Well...",
    },
    {
      response_name: "satisfaction",
      order: 3,
      choice_name: "negative",
      text: "👎 I don't like this answer.",
    },
    {
      response_name: "retry",
      order: 1,
      choice_name: true,
      text: "Yes, please.",
    },
    {
      response_name: "retry",
      order: 2,
      choice_name: false,
      text: "No, I'm done.",
    },
    {
      response_name: "ready",
      order: 1,
      choice_name: true,
      text: "Definitely",
    },
    {
      response_name: "ready",
      order: 2,
      choice_name: false,
      text: "No, I'm not ready.",
    },
    {
      response_name: "pray",
      order: 1,
      choice_name: true,
      text: "🙏 Amen",
    },
    {
      response_name: "pray",
      order: 2,
      choice_name: false,
      text: "🙄 I don't want to.",
    },
  ],
};
